services:
  web-api:
    container_name: unicollab-api
    build:
      context: ./src/Saas.Api
      dockerfile: Dockerfile
    environment: 
      UNICOLLAB_ConnectionStrings__Database: "Data Source=host.docker.internal,5433; Initial Catalog=UniCollab; User Id=sa; Password=YourStrong(!)Password; TrustServerCertificate=True; Encrypt=False; Connection Timeout=30;"
    ports:
      - "4000:8080"
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: unicollab-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "5433:1433"
    environment:
      SA_PASSWORD: "YourStrong(!)Password"
      ACCEPT_EULA: "Y"
    restart: no
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -U sa -P $${SA_PASSWORD} -C -Q "SELECT 1" -b -o /dev/null
      start_period: 5s
      timeout: 5s
      interval: 8s
      retries: 3