services:
  web-api:
    container_name: unicollab-api
    build:
      context: ./src
      dockerfile: Dockerfile
    environment: 
      UNICOLLAB_ConnectionStrings__Database: "Host=host.docker.internal;Port=5433;Database=UniCollab;User Id=postgres;Password=abc123!;"
    ports:
      - "4000:8080"
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: unicollab-db
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "abc123!"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      start_period: 2s
      timeout: 5s
      interval: 1s
      retries: 5
      
volumes:
  postgres-data: