services:
  
  website:
    container_name: unicollab-website
    build:
      context: ../../website
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - web-api
  
  web-api:
    container_name: unicollab-api
    build:
      context: ./Saas.Api
      dockerfile: Dockerfile
    ports:
      - "4000:8080"
    depends_on:
      - database

  database:
    container_name: unicollab-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "5433:1433"
    environment:
      SA_PASSWORD: "YourStrong(!)Password"
      ACCEPT_EULA: "Y"